version: '3.8'

services:
  nextjs:
    container_name: nextjs_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

    networks:
      default:
        ipv4_address: 172.23.0.2

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
